POST https://api.chc.dota2unofficial.com/api/lua/match/suggestion
Content-Type: application/json
Dedicated-Server-Key: Dev_Animus_duQc0Q+NouevGQ

{
  "steamId": "76561198132422587",
  "content": "testing feedback after bot reboot",
  "customGame": "CustomHeroClash",
  "supporterLevel": 2
}

###

POST https://api.chc.dota2unofficial.com/api/lua/match/send_chat_message
Content-Type: application/json
Dedicated-Server-Key: Dev_Animus_duQc0Q+NouevGQ

{
  "steamId": "76561198132422587",
  "customGame": "CustomHeroClash",
  "steamName": "Dummy",
  "text": "no one hears me!",
  "anon": true,
  "supporterLevel": 2
}

###

POST https://api.chc.dota2unofficial.com/api/lua/match/poll_chat_messages
Content-Type: application/json
Dedicated-Server-Key: Dev_Animus_duQc0Q+NouevGQ

{
  "customGame": "CustomHeroClash"
}

###